// surfaces/dashboard/src/lib/components/ontology/ProposalInbox.svelte
<script lang="ts">
import {
	type OntologyProposalRecord,
	applyOntologyProposal,
	listOntologyProposals,
	rejectOntologyProposal,
	scanForDuplicateIdentities,
} from "$lib/api";
import { Check, ChevronDown, RefreshCw, Search, X } from "$lib/icons";
import { proposalHeadline, proposalEvidenceLines } from "./proposal-inbox-data";

interface Props {
	agentId?: string;
}
const { agentId = "default" }: Props = $props();

let proposals = $state<OntologyProposalRecord[]>([]);
let loading = $state(false);
let loadError = $state<string | null>(null);
let busyId = $state<string | null>(null);
let rowError = $state<Record<string, string>>({});
let expanded = $state<Record<string, boolean>>({});

async function load(): Promise<void> {
	loading = true;
	loadError = null;
	try {
		proposals = await listOntologyProposals(agentId, "pending", 100);
	} catch (err) {
		loadError = err instanceof Error ? err.message : "Could not load proposals";
	} finally {
		loading = false;
	}
}

// Re-runs whenever the inspected agent changes.
$effect(() => {
	void agentId;
	void load();
});

let scanning = $state(false);
let scanNote = $state<string | null>(null);

async function scan(): Promise<void> {
	scanning = true;
	scanNote = null;
	const result = await scanForDuplicateIdentities(agentId);
	scanning = false;
	if (!result.ok) {
		scanNote = result.error ?? "Scan failed";
		return;
	}
	// A candidate already queued or already rejected never reappears, so a scan
	// finding nothing new is the steady state. Blocked ones are reported
	// separately: they were found and deliberately not written, which reads as a
	// silent failure otherwise.
	const blocked = result.skipped ? `, ${result.skipped} blocked` : "";
	scanNote = result.written === 0 ? `No new candidates${blocked || " to add"}` : `+${result.written} new${blocked}`;
	await load();
}

async function decide(proposal: OntologyProposalRecord, decision: "apply" | "reject"): Promise<void> {
	busyId = proposal.id;
	const result =
		decision === "apply"
			? await applyOntologyProposal(agentId, proposal.id)
			: await rejectOntologyProposal(agentId, proposal.id, "rejected from dashboard");
	busyId = null;
	if (!result.ok) {
		rowError = { ...rowError, [proposal.id]: result.error ?? "Failed" };
		return;
	}
	// The row leaves the pending queue either way, so drop it rather than refetch.
	const { [proposal.id]: _dropped, ...rest } = rowError;
	rowError = rest;
	proposals = proposals.filter((item) => item.id !== proposal.id);
}
</script>

<section class="inbox">
	<header>
		<h2>Proposals<span class="count">{proposals.length}</span></h2>
		<div class="header-actions">
			<button
				type="button"
				class="icon"
				onclick={() => scan()}
				disabled={scanning}
				aria-label="Scan for duplicate identities"
				title="Scan for duplicate identities"
			>
				<Search size={13} class={scanning ? "spin" : ""} />
			</button>
			<button type="button" class="icon" onclick={() => load()} disabled={loading} aria-label="Refresh proposals">
				<RefreshCw size={13} class={loading ? "spin" : ""} />
			</button>
		</div>
	</header>

	{#if scanNote}<p class="scan-note">{scanNote}</p>{/if}

	{#if loadError}
		<p class="empty error">{loadError}</p>
	{:else if loading && proposals.length === 0}
		<p class="empty">Loading…</p>
	{:else if proposals.length === 0}
		<p class="empty">Nothing pending.</p>
	{/if}

	<ul>
		{#each proposals as proposal (proposal.id)}
			{@const evidence = proposalEvidenceLines(proposal)}
			<li>
				<div class="row">
					<span class="operation">{proposal.operation.replace(/_/g, " ")}</span>
					<span class="confidence" class:low={proposal.confidence < 0.6}>
						{Math.round(proposal.confidence * 100)}%
					</span>
					{#if proposal.risk}<span class="risk">{proposal.risk}</span>{/if}
				</div>

				<p class="headline">{proposalHeadline(proposal)}</p>
				{#if proposal.rationale}<p class="rationale">{proposal.rationale}</p>{/if}

				{#if evidence.length > 0}
					<button type="button" class="evidence-toggle" onclick={() => (expanded = { ...expanded, [proposal.id]: !expanded[proposal.id] })}>
						<ChevronDown size={11} class={expanded[proposal.id] ? "open" : ""} />
						{evidence.length} evidence
					</button>
					{#if expanded[proposal.id]}
						<ul class="evidence">
							{#each evidence as line, index (index)}
								<li>{line}</li>
							{/each}
						</ul>
					{/if}
				{/if}

				{#if rowError[proposal.id]}<p class="row-error">{rowError[proposal.id]}</p>{/if}

				<div class="actions">
					<button type="button" class="apply" disabled={busyId === proposal.id} onclick={() => decide(proposal, "apply")}>
						<Check size={12} /> Apply
					</button>
					<button type="button" class="reject" disabled={busyId === proposal.id} onclick={() => decide(proposal, "reject")}>
						<X size={12} /> Reject
					</button>
				</div>
			</li>
		{/each}
	</ul>
</section>

<style>
	.inbox {
		display: flex;
		flex-direction: column;
		min-height: 0;
		height: 100%;
		width: 320px;
		border-left: 1px solid rgba(148, 163, 184, 0.16);
		background: #05070f;
		color: #cbd5f5;
		font-size: 12px;
	}
	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 10px 12px;
		border-bottom: 1px solid rgba(148, 163, 184, 0.14);
	}
	h2 {
		display: flex;
		align-items: center;
		gap: 6px;
		margin: 0;
		font-size: 12px;
		font-weight: 600;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: #94a3b8;
	}
	.count {
		padding: 1px 6px;
		border-radius: 999px;
		background: rgba(212, 160, 23, 0.16);
		color: #d4a017;
		font-size: 11px;
	}
	.header-actions {
		display: flex;
		gap: 2px;
	}
	.scan-note {
		margin: 0;
		padding: 6px 12px;
		border-bottom: 1px solid rgba(148, 163, 184, 0.08);
		color: #64748b;
		font-size: 11px;
	}
	.icon {
		display: grid;
		place-items: center;
		width: 22px;
		height: 22px;
		border: none;
		border-radius: 5px;
		background: transparent;
		color: #64748b;
		cursor: pointer;
	}
	.icon:hover:not(:disabled) {
		background: rgba(148, 163, 184, 0.12);
		color: #cbd5f5;
	}
	ul {
		list-style: none;
		margin: 0;
		padding: 0;
		/* `min-height: 0` is what actually makes this scroll: a flex item's
		   default `min-height: auto` sizes it to its content, so the list grew
		   past the panel and every row below the fold became unclickable. */
		flex: 1;
		min-height: 0;
		overflow-y: auto;
	}
	.evidence {
		flex: none;
		overflow: visible;
	}
	li {
		padding: 10px 12px;
		border-bottom: 1px solid rgba(148, 163, 184, 0.08);
	}
	.row {
		display: flex;
		align-items: center;
		gap: 6px;
		margin-bottom: 5px;
	}
	.operation {
		font-size: 10px;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		color: #64748b;
	}
	.confidence {
		font-variant-numeric: tabular-nums;
		font-size: 10px;
		color: #34d399;
	}
	.confidence.low {
		color: #d4a017;
	}
	.risk {
		font-size: 10px;
		color: #f87171;
	}
	.headline {
		margin: 0 0 4px;
		color: #e2e8f0;
		line-height: 1.4;
		overflow-wrap: anywhere;
	}
	.rationale {
		margin: 0 0 6px;
		color: #64748b;
		font-size: 11px;
		line-height: 1.4;
	}
	.evidence-toggle {
		display: inline-flex;
		align-items: center;
		gap: 3px;
		padding: 0;
		border: none;
		background: transparent;
		color: #64748b;
		font-size: 11px;
		cursor: pointer;
	}
	.evidence-toggle:hover {
		color: #cbd5f5;
	}
	.evidence {
		margin: 4px 0 0;
		padding-left: 10px;
		border-left: 1px solid rgba(148, 163, 184, 0.18);
	}
	.evidence li {
		padding: 2px 0;
		border: none;
		color: #94a3b8;
		font-size: 11px;
		line-height: 1.4;
		overflow-wrap: anywhere;
	}
	.actions {
		display: flex;
		gap: 6px;
		margin-top: 8px;
	}
	.actions button {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		padding: 3px 9px;
		border: 1px solid transparent;
		border-radius: 5px;
		background: rgba(148, 163, 184, 0.1);
		color: #cbd5f5;
		font-size: 11px;
		cursor: pointer;
	}
	.actions button:disabled {
		opacity: 0.5;
		cursor: default;
	}
	.actions .apply:hover:not(:disabled) {
		border-color: rgba(52, 211, 153, 0.5);
		color: #34d399;
	}
	.actions .reject:hover:not(:disabled) {
		border-color: rgba(248, 113, 113, 0.5);
		color: #f87171;
	}
	.empty {
		margin: 0;
		padding: 14px 12px;
		color: #64748b;
	}
	.empty.error {
		color: #f87171;
	}
	.row-error {
		margin: 6px 0 0;
		color: #f87171;
		font-size: 11px;
		line-height: 1.4;
	}
	:global(.inbox .spin) {
		animation: spin 0.9s linear infinite;
	}
	:global(.inbox .open) {
		transform: rotate(180deg);
	}
	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>

// surfaces/dashboard/src/components/ontology/proposal-inbox.tsx
import { useCallback, useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import {
	applyOntologyProposal,
	listOntologyProposals,
	rejectOntologyProposal,
	scanForDuplicateIdentities,
	type OntologyProposalRecord,
} from "@/lib/ontology-api";
import { proposalEvidenceLines, proposalHeadline } from "./proposal-inbox-data";

/** Anything above this reads as a machine-certain claim; below it, a guess. */
const HIGH_CONFIDENCE = 0.8;

function confidenceLabel(confidence: number): { text: string; tone: string } {
	if (confidence >= HIGH_CONFIDENCE) return { text: "high", tone: "text-[oklch(0.8_0.15_150)]" };
	if (confidence >= 0.55) return { text: "medium", tone: "text-[oklch(0.82_0.14_85)]" };
	return { text: "low", tone: "text-muted-foreground" };
}

/**
 * Pending ontology proposals, docked opposite the entity drawer. Merges are
 * destructive and irreversible, so they are the one operation that never
 * applies itself — this queue is the only place they are decided.
 */
export function ProposalInbox({
	agentId,
	open,
	onClose,
	onDecided,
}: {
	agentId: string;
	open: boolean;
	onClose: () => void;
	/** Applied merges rewrite aliases, so an open identity panel is stale after. */
	onDecided?: () => void;
}) {
	const [items, setItems] = useState<OntologyProposalRecord[]>([]);
	const [loading, setLoading] = useState(false);
	const [listError, setListError] = useState<string | null>(null);
	const [rowError, setRowError] = useState<Record<string, string>>({});
	const [busy, setBusy] = useState<string | null>(null);
	const [expanded, setExpanded] = useState<string | null>(null);
	const [scanning, setScanning] = useState(false);
	const [scanNote, setScanNote] = useState<string | null>(null);

	const load = useCallback(async () => {
		setLoading(true);
		setListError(null);
		try {
			setItems(await listOntologyProposals(agentId, "pending", 50));
		} catch (err) {
			setListError(err instanceof Error ? err.message : "Proposals unavailable");
		} finally {
			setLoading(false);
		}
	}, [agentId]);

	useEffect(() => {
		if (open) void load();
	}, [open, load]);

	const decide = async (id: string, decision: "apply" | "reject") => {
		setBusy(id);
		setRowError((prev) => {
			const next = { ...prev };
			delete next[id];
			return next;
		});
		const result =
			decision === "apply" ? await applyOntologyProposal(agentId, id) : await rejectOntologyProposal(agentId, id);
		setBusy(null);
		if (!result.ok) {
			// A refused decision reports against its own row — the rest of the
			// queue is still actionable and reloading would hide the reason.
			setRowError((prev) => ({ ...prev, [id]: result.error ?? "Decision failed" }));
			return;
		}
		setItems((prev) => prev.filter((item) => item.id !== id));
		onDecided?.();
	};

	const scan = async () => {
		setScanning(true);
		setScanNote(null);
		const result = await scanForDuplicateIdentities(agentId, 40);
		setScanning(false);
		if (!result.ok) {
			setScanNote(result.error ?? "Scan failed");
			return;
		}
		const written = result.written ?? 0;
		// Found-but-not-written is the generator refusing an unsafe merge. Folding
		// that into "nothing new" reads as a silent failure.
		const blocked = Math.max(0, (result.found ?? 0) - written);
		setScanNote(
			written > 0
				? `${written} new candidate${written === 1 ? "" : "s"}${blocked > 0 ? `, ${blocked} blocked` : ""}`
				: `No new candidates${blocked > 0 ? `, ${blocked} blocked` : ""}`,
		);
		if (written > 0) await load();
	};

	return (
		<aside className={cn("graph-inbox", open && "show")} aria-label="Ontology review queue">
			<header className="oi-head">
				<div className="min-w-0 flex-1">
					<span className="gr-label">Review queue</span>
					<div className="gr-title">
						{items.length} pending
						{loading && <span className="ml-2 font-normal text-[11px] text-muted-foreground">loading…</span>}
					</div>
				</div>
				<button type="button" className="oi-btn" disabled={scanning} onClick={() => void scan()}>
					{scanning ? "Scanning…" : "Scan"}
				</button>
				<button type="button" className="gr-close" aria-label="Close review queue" onClick={onClose}>
					<svg
						viewBox="0 0 24 24"
						width="15"
						height="15"
						fill="none"
						stroke="currentColor"
						strokeWidth={2}
						strokeLinecap="round"
					>
						<title>Close</title>
						<path d="M18 6 6 18M6 6l12 12" />
					</svg>
				</button>
			</header>

			{scanNote && <p className="oi-note">{scanNote}</p>}
			{listError && <p className="oi-note oi-note--bad">{listError}</p>}

			{/* min-h-0 is load-bearing: a flex item defaults to min-height:auto, so
			    overflow-y alone leaves the list overflowing and unclickable. */}
			<div className="oi-list min-h-0">
				{!loading && items.length === 0 && !listError && (
					<p className="oi-empty">Nothing pending. Scan looks for duplicate identities the graph has not merged.</p>
				)}
				{items.map((proposal) => {
					const confidence = confidenceLabel(proposal.confidence);
					// Evidence lines are literal quotes with no id of their own and the
					// list never reorders, so position is the identity.
					const evidence = proposalEvidenceLines(proposal).map((text, i) => ({ id: `${proposal.id}:${i}`, text }));
					const isOpen = expanded === proposal.id;
					return (
						<article key={proposal.id} className="oi-row">
							<div className="oi-row-top">
								<code className="oi-op">{proposal.operation}</code>
								<span className={cn("oi-conf", confidence.tone)}>
									{confidence.text} · {Math.round(proposal.confidence * 100)}%
								</span>
							</div>
							<p className="oi-headline">{proposalHeadline(proposal)}</p>
							{proposal.rationale && <p className="oi-rationale">{proposal.rationale}</p>}

							{evidence.length > 0 && (
								<>
									<button
										type="button"
										className="oi-eviclose"
										onClick={() => setExpanded(isOpen ? null : proposal.id)}
										aria-expanded={isOpen}
									>
										{isOpen ? "Hide" : "Show"} evidence ({evidence.length})
									</button>
									{isOpen && (
										<ul className="oi-evidence">
											{evidence.map((line) => (
												<li key={line.id}>{line.text}</li>
											))}
										</ul>
									)}
								</>
							)}

							{rowError[proposal.id] && <p className="oi-note oi-note--bad">{rowError[proposal.id]}</p>}

							<div className="oi-actions">
								<button
									type="button"
									className="oi-btn oi-btn--apply"
									disabled={busy === proposal.id}
									onClick={() => void decide(proposal.id, "apply")}
								>
									Apply
								</button>
								<button
									type="button"
									className="oi-btn"
									disabled={busy === proposal.id}
									onClick={() => void decide(proposal.id, "reject")}
								>
									Reject
								</button>
							</div>
						</article>
					);
				})}
			</div>
		</aside>
	);
}
